"""Groq text generation for prompt writing.

Groq serves open-weight models (Llama / Kimi / Qwen / GPT-OSS) at very high
tokens/sec — we use it for the fit-aware prompt-writing step only. The actual
image is still generated by Gemini 2.5 Flash Image (Nano Banana).

Requires:
    pip install groq
    .env must contain:  GROQ_API_KEY=...
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

TEXT_MODEL_NAME = "llama-3.3-70b-versatile"


def _get_client() -> Groq:
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("No Groq API key found. Set `GROQ_API_KEY` in your .env file.")
    return Groq(api_key=api_key)


def generate_text(prompt: str) -> str:
    client = _get_client()
    response = client.chat.completions.create(
        model=TEXT_MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )
    return (response.choices[0].message.content or "").strip()


def generate_text_stream(prompt: str):
    """Yield text chunks as Groq streams them — for live UI typing effect."""
    client = _get_client()
    stream = client.chat.completions.create(
        model=TEXT_MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        stream=True,
    )
    for chunk in stream:
        content = chunk.choices[0].delta.content
        if content:
            yield content
